ksrmsangati/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ksrmsangati.Models;
using ksrmsangati.Data;
using Newtonsoft.Json;
using PaulMiami.AspNetCore.Mvc.Recaptcha;
using System.Security.Cryptography;
using MimeKit;
using MailKit.Net.Smtp;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;

namespace ksrmsangati.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IHostingEnvironment _environment;
        private ILogger _logger;
        public EventsController(ApplicationDbContext db, IHostingEnvironment environment, ILoggerFactory loggerFactory)
        {
            _db = db;
            _environment = environment;
            _logger = loggerFactory.CreateLogger(typeof(EventsController));
        }
        public IActionResult Index()
        {
            IList<EventDTO> events = _db.Events.Select(e =>
               new EventDTO
               {
                   EventId = e.EventId,
                   EventName = e.EventName,
                   EventTime = e.EventTime,
                    //Teams = e.Teams,
                    Venue = e.Venue
               }

               ).ToList();
            return View(events);
        }

        [HttpGet]
        public IActionResult Event(int eventId)
        {
            EventDTO e = _db.Events.Select(
                a => new EventDTO
                {
                    EventId = a.EventId,
                    EventName = a.EventName,
                    EventTime = a.EventTime,
                    Venue = a.Venue
                }
                ).First(x => x.EventId == eventId);
            return View(e);
        }

        [HttpGet]
        public IActionResult Register(int eventId)
        {
            try
            {
                EventDTO e = _db.Events.Select(
                a => new EventDTO
                {
                    EventId = a.EventId,
                    EventName = a.EventName,
                    EventTime = a.EventTime,
                    Venue = a.Venue
                }
                ).First(x => x.EventId == eventId);
                RegisterBindingModel model = new RegisterBindingModel { EventId = eventId, EventName = e.EventName };
                //ViewData["EventId"] = eventId;
                //ViewData["ReturnUrl"] = Url.Action("Register", "Events", new { eventId = model.EventId });
                return View(model);
            }
            catch(Exception e)
            {
                return View(null);
            }
        }

        [ValidateRecaptcha]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([FromForm]RegisterBindingModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsFileUploaded = false;
                if(model.EventId == 101 )
                {
                    if(model.FileUp==null)
                    {
                        ModelState.AddModelError("FileUp", "Please select presentation to be uploaded");
                        return View(model);
                    }
                    IsFileUploaded = true;
                }
                Team team = new Team
                {
                    TeamName = model.TeamName,
                    RegistrationTime = DateTime.UtcNow.AddHours(5).AddMinutes(30),
                    CollegeName = model.CollegeName,
                    EventId = model.EventId,
                    Email = model.Email,
                    Member1 = model.Member1,
                    Member2 = model.Member2,
                    Member3 = model.Member3,
                    Member4 = model.Member4,
                    Member5 = model.Member5,
                    PhoneNumber = model.PhoneNumber,
                    IsConfirmed = false
                };

                team.MemberCount = 2;
                if (model.Member3 != "" && model.Member3!=null)
                {
                    team.MemberCount++;
                    if (model.Member4 != "" && model.Member4!=null)
                        team.MemberCount++;
                }

                Random rdm = new Random();
                var no = rdm.Next(100000, 999999);
                team.Pin = no.ToString();
                
                _db.Teams.Add(team);
                _db.SaveChanges();

                _db.Entry(team).Reload();
                string eventName = _db.Events.Single(ev => ev.EventId == model.EventId).EventName;
                TeamDTO t = new TeamDTO
                {
                    TeamId = team.TeamId,
                    CollegeName = team.CollegeName,
                    Email = team.Email,
                    EventId = team.EventId,
                    IsConfirmed = team.IsConfirmed,
                    Member1 = team.Member1,
                    Member2 = team.Member2,
                    Member3 = team.Member3,
                    Member4 = team.Member4,
                    Member5 = team.Member5,
                    MemberCount = team.MemberCount,
                    PhoneNumber = team.PhoneNumber,
                    RegistrationTime = team.RegistrationTime,
                    TeamName = team.TeamName,
                    EventName = eventName
                };

                if (IsFileUploaded)
                {
                    var uploads = Path.Combine(_environment.WebRootPath, "uploads");
                    var file = model.FileUp;
                    if (file.Length > 0)
                    {
                        using (var fileStream = new FileStream(Path.Combine(uploads, t.TeamId + "_" + file.FileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    }
                }

                SendMail(team.Pin,t);

                TempData["Team"] = JsonConvert.SerializeObject(t);
                return RedirectToAction("RegisterSuccess");
            }
            //ViewData["ReturnUrl"] = Url.Action("Register", "Events", new { eventId = model.EventId });
            EventDTO e = _db.Events.Select(
                a => new EventDTO
                {
                    EventId = a.EventId,
                    EventName = a.EventName,
                    EventTime = a.EventTime,
                    Venue = a.Venue
                }
                ).First(x => x.EventId == model.EventId);
            model.EventName = e.EventName;
            return View(model);
        }

        [HttpGet]
        public IActionResult RegisterSuccess()
        {
            TeamDTO team = JsonConvert.DeserializeObject<TeamDTO>(TempData["Team"].ToString());
            string eventName = _db.Events.Single(ev => ev.EventId == team.EventId).EventName;
            team.EventName = eventName;
            return View(team);
        }

        public async void SendMail(string pin,TeamDTO t)
        {
            try
            {
                //From Address  
                string FromAddress = "sangati2k18@gmail.com";
                string FromAdressTitle = "Sangati 2k18";
                //To Address  
                string ToAddress = t.Email;
                string ToAdressTitle = "";
                string Subject = "Welcome to Sangati 2k18.";
                string BodyContent = @"Cheers Team!
                                        <br>
                                        You have succesfully registered to Sangati for Event - " + t.EventName.ToUpper() + ". <br>" +
                                            "Your registration ID is " + t.TeamId +
                                            ". For any queries feel free to visit <a href=\"http://ksrmsangati.com\">ksrmsangati.com</a>" +
                                            @" <br/> It's a pleasure to have you on board with us.
                                                        <br/> We at Sangati believe in providing an ambience that helps young entrepreneurs to bloom and make a strong forced bridge that not onlyempowers rural markets but also helps such rural talents dig its rott deep into the marketing sectors. <br/>
                                                        <br/> With all that said and done, 
                                                            <br/> MAY THE BEST TEAM WIN!";
                   
                //Smtp Server  
                string SmtpServer = "smtp.gmail.com";
                //Smtp Port Number  
                int SmtpPortNumber = 587;

                var mimeMessage = new MimeMessage();
                mimeMessage.From.Add(new MailboxAddress(FromAdressTitle, FromAddress));
                mimeMessage.To.Add(new MailboxAddress(ToAdressTitle, ToAddress));
                mimeMessage.Subject = Subject;
                mimeMessage.Body = new TextPart("html")
                {
                    Text = BodyContent

                };

                //SELF MAIL

                //From Address  
                string FromAddressSelf = "sangati2k18@gmail.com";
                string FromAdressTitleSelf = "Sangati 2k18";
                //To Address  
                string ToAddressSelf = "sangati2k18@gmail.com";
                string ToAdressTitleSelf = "";
                string SubjectSelf = "New Registration for event ";
                string BodyContentSelf = @"Cheers Team!
                                        <br>
                                        New team registered to Sangati for Event - " + t.EventName.ToUpper() + ". <br>" +
                                            "Registration ID is " + t.TeamId + "<br>"+
                                            "COLLEGE : "+t.CollegeName + " <br>" + 
                                           
                                            "" +
                                            @" ";

ksrmsangati/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - KSRM Sangati</title>
    <!--fonts-->
    <link href='http://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

    @RenderSection("Links",required:false)

    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Music World Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
		Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <!-- js -->
    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <!-- js -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>

    <!-- start-smoth-scrolling -->
</head>
<body>
    <!-- header -->
    <div id="particle"></div>
    <div id="overlay" class="header">
        <div class="container">
            <div class="header-left">
                <a href="~/">SANGATI 2k17</a>
            </div>
            <div class="navigation">
                <nav class="navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"> </span>
                            <span class="icon-bar"> </span>
                            <span class="icon-bar"> </span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="hvr-bounce-to-bottom active"><a asp-controller="Home" asp-action="Index">HOME <span class="sr-only">(current)</span></a></li>
                            <li class="hvr-bounce-to-bottom"><a asp-controller="Home" asp-action="About">ABOUT</a></li>
                           <!-- <li class="hvr-bounce-to-bottom"><a asp-controller="Events" asp-action="Index">EVENTS</a></li> -->
                            <li class="hvr-bounce-to-bottom">
                                <a href="~/events">EVENTS</a>
                                @*<li class="hvr-bounce-to-bottom"><a href="#sponsors">SPONSORS</a></li>*@
                            <li class="hvr-bounce-to-bottom"><a asp-controller="Home" asp-action="Gallery">GALLERY</a></li>
                            <li class="hvr-bounce-to-bottom"><a href="#contact">CONTACT</a></li>
                        </ul>
                        <div class="clearfix"> </div>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- //header -->
    
        <div id="overlay" class="body-content">
            @RenderBody()
            
        </div>
    <hr />
        <!-- footer -->
        <div class="footer">
            <div id="contact" class="container">
                <div class="footer-grids">
                    <div class="col-md-3 footer-grid">
                        <h4>ADDRESS</h4>
                        <ul>
                            <li>KIIT School Of Rural Management</li>
                            <li>Bhubaneswar </li>
                        </ul>
                    </div>
                    <div class="col-md-6 footer-grid">
                        <h4>GET IN TOUCH</h4>
                    <div class="col-sm-6 footer-grid">

                        <ul>
                            <li>Sangmeshwar Biradar</li>
                            <li>Mobile: +918984616204</li>
                            <li>Email: <a href="mailto:16201007@ksrm.ac.in">16201007@ksrm.ac.in </a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 footer-grid">
                        <ul>
                            <li>Saibal Paul</li>
                            <li>Mobile: +918051039413</li>
                            <li>Email: <a href="mailto:16201028@ksrm.ac.in">16201028@ksrm.ac.in </a></li>
                        </ul>
                    </div>
                        </div>
                    <div class="col-md-3 footer-grid">
                        <h3><a asp-controller="Home" asp-action="Index">SANGATI 2k17</a></h3>
                        <div class="col-sm-12 footer-grid">

                            <ul>
                                <li>Ms Snigdha Mohanty</li>
                                <li>Mobile: +917377240015</li>
                                <li>KIIT School of Rural Management</li>
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- //footer -->
        <!-- copy -->
        <div class="copy-right">
            <div class="container">
                <p> &copy; 2017 KSRM Sangati. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
            </div>
        </div>
        <!-- copy -->
        <!-- smooth scrolling -->
        <script type="text/javascript">
            $(document).ready(function () {
                /*
                    var defaults = {
                    containerID: 'toTop', // fading element id
                    containerHoverID: 'toTopHover', // fading element hover id
                    scrollSpeed: 1200,
                    easingType: 'linear'
                    };
                */
                $().UItoTop({ easingType: 'easeOutQuart' });
            });
        </script>
        <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
        <!-- //smooth scrolling -->
        <!-- for bootstrap working -->
        <script src="~/js/bootstrap.js"></script>
        <!-- //for bootstrap working -->

    

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script>
            var options = { "particles": { "number": { "value": 90, "density": { "enable": true, "value_area": 552.4033491425909 } }, "color": { "value": "#ffffff" }, "shape": { "type": "circle", "stroke": { "width": 0, "color": "#000000" }, "polygon": { "nb_sides": 5 }, "image": { "src": "img/github.svg", "width": 70, "height": 100 } }, "opacity": { "value": 1, "random": true, "anim": { "enable": true, "speed": 1, "opacity_min": 0.1, "sync": false } }, "size": { "value": 2, "random": true, "anim": { "enable": false, "speed": 40, "size_min": 0.1, "sync": false } }, "line_linked": { "enable": true, "distance": 150, "color": "#ffffff", "opacity": 0.4, "width": 1 }, "move": { "enable": true, "speed": 1.5782952832645452, "direction": "none", "random": true, "straight": false, "out_mode": "out", "bounce": false, "attract": { "enable": false, "rotateX": 600, "rotateY": 1200 } } }, "interactivity": { "detect_on": "canvas", "events": { "onhover": { "enable": false, "mode": "repulse" }, "onclick": { "enable": true, "mode": "repulse" }, "resize": true }, "modes": { "grab": { "distance": 400, "line_linked": { "opacity": 1 } }, "bubble": { "distance": 400, "size": 40, "duration": 2, "opacity": 8, "speed": 3 }, "repulse": { "distance": 200, "duration": 0.4 }, "push": { "particles_nb": 4 }, "remove": { "particles_nb": 2 } } }, "retina_detect": false };
            particlesJS("particle", options);
    </script>

    @*<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>*@

        @RenderSection("Scripts", required: false)
</body>
</html>