ksrmsangati/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ksrmsangati.Data;
using ksrmsangati.Models;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace ksrmsangati.Controllers
{
    
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db;
        private ILogger _logger;
        private IHostingEnvironment _environment;

        public AdminController(ApplicationDbContext db, ILoggerFactory loggerFactory, IHostingEnvironment env)
        {
            _db = db;
            _logger = loggerFactory.CreateLogger(typeof(AdminController));
            _environment = env;
        }
        public IActionResult Index()
        {
            //_logger.LogError("Admin Section Accessed!");
            //var teams = _db.Teams.Include(t => t.Event).OrderBy(t=>t.EventId).GroupBy(t=>t.EventId).ToList();

            //var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            //foreach (string file in Directory.EnumerateFiles(
            //uploads,
            //("*"),
            //SearchOption.AllDirectories)
            //)
            //{
            //    // do something

            //}
            return View();
        }
        [HttpPost]
        public IActionResult Index(string pass)
        {
            //_logger.LogError("Admin Section Accessed!");
            //var teams = _db.Teams.Include(t => t.Event).OrderBy(t=>t.EventId).GroupBy(t=>t.EventId).ToList();

            //var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            //foreach (string file in Directory.EnumerateFiles(
            //uploads,
            //("*"),
            //SearchOption.AllDirectories)
            //)
            //{
            //    // do something

            //}
            if(pass=="Makeitbigteam78*")
            {
                var teams = _db.Teams.Include(t => t.Event).OrderBy(t => t.EventId).GroupBy(t => t.EventId).ToList();
                return View(teams);
            }
            return View();
        }

        public IActionResult DownloadWriteup(int id)
        {
            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            var file = Directory.GetFiles(uploads, (id + "_*"));
            if (file.Length > 0)
            {
                var fileName = Path.GetFileName(file[0]);
                var fs = System.IO.File.OpenRead(file[0]);
                return File(fs, "application/octet-stream", fileName);
            }
            return RedirectToAction("Index");
        }
    }
}

ksrmsangati/Views/Admin/Index.cshtml
@model List<IGrouping<int, Team>>
@{
    ViewData["Title"] = "Index";

    Layout = null;

}

@*<link href="~/css/bootstrap.css" rel="stylesheet">

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>KSRM |Registration</title>
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Poiret+One" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600|Montserrat:200,300,400" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="icon" type="image/png " href="favico.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="~/registerc.css">
    <link rel="stylesheet" href="~/assets/css/admin.css">
</head>
<body>

    @if (Model != null)
    {
        @foreach (var g in Model)
        {
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            @g.FirstOrDefault().Event.EventName
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table class="table table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>College</th>
                                        <th>Email</th>
                                        <th>Number</th>
                                        <th>Members</th>
                                        <th>Writeup</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var team in g.ToList())
                                    {
                                        <tr class="odd gradeX">
                                            <td>@team.TeamId</td>
                                            <td>@team.TeamName</td>
                                            <td>@team.CollegeName</td>
                                            <td>@team.PhoneNumber</td>
                                            <td class="center">@team.Email</td>
                                            <td>
                                                @team.Member1,
                                                <br /> @team.Member2
                                                <br /> @team.Member3
                                                <br /> @team.Member4

                                            </td>
                                            @if (team.EventId == 101)
                                            {
                                            <td>
                                                <a asp-controller="Admin" asp-action="DownloadWriteup" asp-route-id="@team.TeamId">Download</a>
                                            </td>
                                            }
                                        </tr>
                                    }

                                </tbody>
                            </table>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        }
    }

    else
    {
        <form asp-controller="Admin" asp-action="Index" asp-route-returnurl="@ViewData["ReturnUrl"]" enctype="multipart/form-data" method="post" class="form-horizontal">
            <br />
            <h2>Enter password</h2>
            <input type="password" name="pass" class="form-control" />
            <input type="submit" class="form-control" />

        </form>
    }

</body>
</html>